[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mm-routing-moea"
version = "2.0.0"
description = "Multi-Objective Evolutionary Algorithm for Multimodal Routing"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "networkx>=3.1",
    "numpy>=1.24",
    "pandas>=2.0",
    "pymoo>=0.6.0.1",
    "scikit-learn>=1.2.2",
    "osmnx>=1.9.1",
    "tqdm>=4.65.0",
    "pytest>=7.3.1"
]
