import json
import logging
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

# We can import the existing logic from the main pipeline or replicate the specific logic for isolation
from src.pipeline_V6_smart import audit_and_stabilize_weights

logger = logging.getLogger(__name__)

def run_stabilization(raw_weights_path: str, out_dir: str):
    raw_path = Path(raw_weights_path)
    out_dir_path = Path(out_dir)
    out_dir_path.mkdir(parents=True, exist_ok=True)
    
    logger.info(f"Loading raw Borda-count weights from {raw_path}")
    with open(raw_path, "r", encoding="utf-8") as f:
        raw_weights = json.load(f)
        
    audit = audit_and_stabilize_weights(raw_weights, floor=0.08, blend_uniform=0.20)
    
    # Save the stabilized weights
    stab_path = out_dir_path / "objective_weights_stabilized.json"
    with open(stab_path, "w", encoding="utf-8") as f:
        json.dump(audit.stabilized_weights, f, indent=2)
        
    logger.info(f"Stabilized weights saved to {stab_path}")
    
    # Create comparison table
    comparison = pd.DataFrame([
        {"objective": k, "raw_weight": audit.raw_weights[k], "stabilized_weight": audit.stabilized_weights[k]}
        for k in audit.raw_weights.keys()
    ])
    
    csv_path = out_dir_path / "stabilized_weights_comparison.csv"
    comparison.to_csv(csv_path, index=False)
    logger.info(f"Comparison table saved to {csv_path}")
    
    if audit.warnings:
        logger.warning("Stabilization warnings triggered:")
        for w in audit.warnings:
            logger.warning(f" - {w}")
            
    # Generate visualization
    fig, ax = plt.subplots(figsize=(8, 5))
    x = range(len(comparison))
    width = 0.35
    
    ax.bar([i - width/2 for i in x], comparison["raw_weight"], width, label='Raw Weight', color='#1f77b4')
    ax.bar([i + width/2 for i in x], comparison["stabilized_weight"], width, label='Stabilized Weight', color='#ff7f0e')
    
    ax.set_ylabel('Weight')
    ax.set_title('Priority Stabilization of Objective Weights')
    ax.set_xticks(x)
    ax.set_xticklabels(comparison["objective"].str.capitalize())
    ax.legend()
    
    plot_path = out_dir_path / "stabilization_comparison.png"
    plt.tight_layout()
    plt.savefig(plot_path, dpi=300)
    logger.info(f"Visualization saved to {plot_path}")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    # The raw weights should be generated by pipeline_V6_smart or we can point to a known location
    # If it doesn't exist, we will use a dummy raw weight for demonstration
    raw_path = "outputs_surrogate/objective_weights_raw.json"
    if not Path(raw_path).exists():
        logger.info(f"{raw_path} not found. Creating dummy raw weights for demonstration.")
        Path("outputs_surrogate").mkdir(parents=True, exist_ok=True)
        dummy = {"time": 0.1, "cost": 0.1, "emissions": 0.05, "comfort": 0.75}
        with open(raw_path, "w") as f:
            json.dump(dummy, f)
            
    run_stabilization(raw_path, "outputs_surrogate")
